<?php
/**
 * ReminderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReminderTest Class Doc Comment
 *
 * @category    Class */
// * @description Reminder
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReminderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Reminder"
     */
    public function testReminder()
    {
    }

    /**
     * Test attribute "ticket_reminder_id"
     */
    public function testPropertyTicketReminderId()
    {
    }

    /**
     * Test attribute "ticket_id"
     */
    public function testPropertyTicketId()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }
}
