<?php
/**
 * TicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TicketTest Class Doc Comment
 *
 * @category    Class */
// * @description Ticket
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ticket"
     */
    public function testTicket()
    {
    }

    /**
     * Test attribute "ticket_id"
     */
    public function testPropertyTicketId()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "date_required_by"
     */
    public function testPropertyDateRequiredBy()
    {
    }

    /**
     * Test attribute "severity"
     */
    public function testPropertySeverity()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "ticket_uuid"
     */
    public function testPropertyTicketUuid()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "is_internal"
     */
    public function testPropertyIsInternal()
    {
    }

    /**
     * Test attribute "requestor_group_user_id"
     */
    public function testPropertyRequestorGroupUserId()
    {
    }

    /**
     * Test attribute "assignee_group_user_id"
     */
    public function testPropertyAssigneeGroupUserId()
    {
    }

    /**
     * Test attribute "owner_group_user_id"
     */
    public function testPropertyOwnerGroupUserId()
    {
    }

    /**
     * Test attribute "requestor_name"
     */
    public function testPropertyRequestorName()
    {
    }

    /**
     * Test attribute "owner_name"
     */
    public function testPropertyOwnerName()
    {
    }

    /**
     * Test attribute "assignee_name"
     */
    public function testPropertyAssigneeName()
    {
    }

    /**
     * Test attribute "owner_account_name"
     */
    public function testPropertyOwnerAccountName()
    {
    }

    /**
     * Test attribute "ticket_messages"
     */
    public function testPropertyTicketMessages()
    {
    }
}
