<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePremadeResponse
     *
     * .
     *
     */
    public function testDeletePremadeResponse()
    {
    }

    /**
     * Test case for deleteTicketReminder
     *
     * .
     *
     */
    public function testDeleteTicketReminder()
    {
    }

    /**
     * Test case for deleteTicketTag
     *
     * .
     *
     */
    public function testDeleteTicketTag()
    {
    }

    /**
     * Test case for getPremadeResponse
     *
     * .
     *
     */
    public function testGetPremadeResponse()
    {
    }

    /**
     * Test case for getPremadeResponses
     *
     * .
     *
     */
    public function testGetPremadeResponses()
    {
    }

    /**
     * Test case for getTicket
     *
     * .
     *
     */
    public function testGetTicket()
    {
    }

    /**
     * Test case for getTicketReminder
     *
     * .
     *
     */
    public function testGetTicketReminder()
    {
    }

    /**
     * Test case for getTicketReminders
     *
     * .
     *
     */
    public function testGetTicketReminders()
    {
    }

    /**
     * Test case for getTicketTags
     *
     * .
     *
     */
    public function testGetTicketTags()
    {
    }

    /**
     * Test case for getTickets
     *
     * .
     *
     */
    public function testGetTickets()
    {
    }

    /**
     * Test case for postTicketMessages
     *
     * .
     *
     */
    public function testPostTicketMessages()
    {
    }

    /**
     * Test case for postTicketReminders
     *
     * .
     *
     */
    public function testPostTicketReminders()
    {
    }

    /**
     * Test case for postTickets
     *
     * .
     *
     */
    public function testPostTickets()
    {
    }

    /**
     * Test case for putPremadeResponses
     *
     * .
     *
     */
    public function testPutPremadeResponses()
    {
    }

    /**
     * Test case for putTicketMessages
     *
     * .
     *
     */
    public function testPutTicketMessages()
    {
    }

    /**
     * Test case for putTicketReminders
     *
     * .
     *
     */
    public function testPutTicketReminders()
    {
    }

    /**
     * Test case for putTicketReview
     *
     * .
     *
     */
    public function testPutTicketReview()
    {
    }

    /**
     * Test case for putTicketTags
     *
     * .
     *
     */
    public function testPutTicketTags()
    {
    }

    /**
     * Test case for putTickets
     *
     * .
     *
     */
    public function testPutTickets()
    {
    }
}
